zookeeper:
  image: jplock/zookeeper
  ports: 
    - "2181:2181"
  volumes:
    - /root/sharedata:/root/sharedata
nimbus:
  image: wurstmeister/storm-nimbus:0.9.2
  ports:
    - "3773:3773"
    - "3772:3772"
    - "6627:6627"
  links: 
    - zookeeper:zk
    - kafka:kafka
  volumes:
    - /root/sharedata:/root/sharedata
supervisor:
  image: wurstmeister/storm-supervisor:0.9.2
  ports:
    - "8000:8000"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
    - kafka:kafka
  volumes:
    - /root/sharedata:/root/sharedata
ui:
  image: wurstmeister/storm-ui:0.9.2
  ports:
    - "8080:8080"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
  volumes:
    - /root/sharedata:/root/sharedata
kafka:
  build: .
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.164.60
    KAFKA_CREATE_TOPICS: "log-analysis:1:1"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /root/sharedata:/root/sharedata
openfire:
  image: mdouglas/openfire
  ports:
  - "5222:5222"
  - "5223:5223"
  - "9091:9091"
  - "9090:9090"
  volumes:
    - /root/sharedata:/root/sharedata
